# Generated by Django 4.1.3 on 2022-12-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_profesoress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='curso',
            name='dia',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
