# Generated by Django 4.1.3 on 2022-12-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_remove_curso_fecha_creacion_curso_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='dia',
            new_name='fecha_creacion',
        ),
    ]
