# Generated by Django 4.1.3 on 2022-12-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_dia_curso_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='fecha_creacion',
            new_name='dia_creacion',
        ),
    ]
