# Generated by Django 4.1.3 on 2022-12-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_rename_fecha_creacion_curso_dia_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='comision',
            new_name='camada',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='dia_creacion',
            new_name='numero_dia',
        ),
    ]
